name: talkonomy_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 8.1.1
  get_it: 7.2.0
  flutter_bloc: 8.1.2
  dio: 5.0.2
  dartz: 0.10.1
  shared_preferences: 2.0.18
  retrofit: 4.0.1
  rxdart: 0.27.7
  cupertino_icons: 1.0.2
  json_annotation: 4.8.0
  flash: 2.0.5
  equatable: 2.0.5
  flutter_screenutil: 5.7.0
  google_fonts: 4.0.3
  flutter_dotenv: 5.0.2
  flutter_easyloading: 3.0.5
  flutter_svg: 2.0.3
  retrofit_generator: 5.0.0
  intl: 0.18.0

dev_dependencies:
  json_serializable: 6.6.1
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
